#!/usr/bin/ruby -w
require 'rubygems'
require 'json'

Dir["lib/*.rb"].each {|file| require file }

COMMAND_PATH = 'commands'
SESSION_PATH = 'config/session.json'

if !Commandline::run(ARGV)
  puts "usage: pf <command> <args>"
  puts
  puts "List of commands:"
  puts Commandline::help
  puts
  puts "Use 'pf help <command>' for more information on a specific command." 
end 
